-- Create table for AI content writer tone-style combinations
CREATE TABLE public.ai_content_combinations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tone text NOT NULL,
    style text NOT NULL,
    icon text NOT NULL DEFAULT '📝',
    result text NOT NULL,
    result_myanmar text,
    use_case text NOT NULL,
    use_case_myanmar text,
    example text,
    full_example text,
    display_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid REFERENCES public.profiles(user_id),
    updated_by uuid REFERENCES public.profiles(user_id),
    UNIQUE(tone, style)
);

-- Enable RLS
ALTER TABLE public.ai_content_combinations ENABLE ROW LEVEL SECURITY;

-- Anyone can view active combinations
CREATE POLICY "Anyone can view active combinations"
ON public.ai_content_combinations
FOR SELECT
USING (is_active = true);

-- Admins can manage all combinations
CREATE POLICY "Admins can manage combinations"
ON public.ai_content_combinations
FOR ALL
USING (has_role(auth.uid(), 'admin'))
WITH CHECK (has_role(auth.uid(), 'admin'));

-- Insert default combinations
INSERT INTO public.ai_content_combinations (tone, style, icon, result, result_myanmar, use_case, use_case_myanmar, example, full_example, display_order) VALUES
('Tough Love', 'Persuasive', '🔥', 'Hard-hitting sales copy that challenges readers to face reality and take action', 'စာဖတ်သူကို အမှန်တရားနဲ့ ရင်ဆိုင်စေပြီး လုပ်ဆောင်စေတဲ့ ဆွဲဆောင်မှုရှိတဲ့ စာ', 'Sales pages, wake-up call content, transformation programs', 'အရောင်းစာမျက်နှာ၊ နိုးကြားစေတဲ့ content၊ ပြောင်းလဲရေး program များ', 'မင်းရဲ့ အိပ်မက်တွေက အိပ်မက်အတိုင်းပဲ ကျန်ခဲ့မယ်...', E'# 🔥 Tough Love + Persuasive Example\n\n## ခေါင်းစဉ်: "မင်းရဲ့ အိပ်မက်တွေ ဘာကြောင့် အိပ်မက်အတိုင်းပဲ ကျန်နေတာလဲ"\n\n### Opening (Uncomfortable Truth)\n**Stop lying to yourself.** You\'ve been "planning to start" for how long now? Six months? A year? Five years?\n\nဒီစာကို ဖတ်နေတဲ့ မင်း... **မင်းကိုယ်မင်း လိမ်နေတာ ရပ်လိုက်ပါ။**\n\n"စချင်တယ်၊ စမယ်" ဆိုပြီး ဘယ်နှစ်နှစ် ရှိပြီလဲ? ခြောက်လ? တစ်နှစ်? ငါးနှစ်?\n\n### Pain Amplification\nမင်းနဲ့ အတူတူ စခဲ့တဲ့သူတွေ... အခု ဘယ်ရောက်နေပြီလဲ သိလား?\n\n- သူတို့က ပထမဆုံး ဝင်ငွေရပြီ\n- သူတို့က follower တစ်သောင်းကျော်ပြီ\n- သူတို့က brand deal တွေရနေပြီ\n\n**မင်းက?** နောက်ထပ် "perfect plan" တစ်ခုကို ရေးဆွဲနေတုန်းပဲ။\n\n### The Mirror\nအမှန်တရားကို မျက်နှာချင်းဆိုင် ကြည့်လိုက်ပါ:\n\n> "Perfect timing ဆိုတာ မရှိဘူး။ မင်းက ကြောက်နေတာ။"\n\nကြောက်တာ မှားတာ မဟုတ်ဘူး။ ဒါပေမယ့် ကြောက်လို့ မလုပ်ဘဲ နေတာက... **မင်းဘဝကို သတ်နေတာနဲ့ အတူတူပဲ။**\n\n### Wake-up Call\n**ဒီနေ့ပဲ ဆုံးဖြတ်လိုက်ပါ။**\n\nPerfect မဖြစ်လည်း စလိုက်ပါ။ အဆင်မပြေလည်း တင်လိုက်ပါ။ လူမရီလည်း ပြောလိုက်ပါ။\n\n**မင်းရဲ့ future self က ဒီနေ့ မင်းလုပ်တဲ့ action ကို ကျေးဇူးတင်မှာပါ။**\n\n---\n*ဒီလို Tough Love + Persuasive style က စာဖတ်သူကို uncomfortable ဖြစ်စေပြီး action ယူစေတဲ့ powerful content ဖြစ်ပါတယ်။*', 1),

('Professional', 'Article', '📊', 'Well-researched, authoritative content with data-backed insights', 'သုတေသနအခြေခံ၊ data နဲ့ ထောက်ပံ့ထားတဲ့ ယုံကြည်စိတ်ချရတဲ့ content', 'Industry reports, educational content, thought leadership', 'လုပ်ငန်းသုံး report များ၊ ပညာရေး content၊ thought leadership', 'စစ်တမ်းအရ ၇၈% သော လူငယ်များသည်...', E'# 📊 Professional + Article Example\n\n## ခေါင်းစဉ်: "2024 Myanmar Digital Economy: Growth Trends and Investment Opportunities"\n\n### Executive Summary\nMyanmar''s digital economy has shown remarkable resilience, with **e-commerce transactions increasing by 156%** year-over-year despite economic challenges.\n\n### Key Findings\n\n#### 1. Mobile Payment Adoption\nAccording to recent data from the Central Bank of Myanmar:\n\n| Year | Mobile Payment Users | YoY Growth |\n|------|---------------------|------------|\n| 2022 | 2.1 million | - |\n| 2023 | 4.8 million | 128% |\n| 2024 | 8.2 million | 71% |\n\n#### 2. E-commerce Growth Sectors\n- **Fashion & Apparel**: 45% market share\n- **Electronics**: 28% market share\n- **Food & Grocery**: 18% market share\n\n### Analysis\nThe data suggests a fundamental shift in consumer behavior...\n\n### Recommendations\n1. **For Investors**: Focus on fintech and logistics infrastructure\n2. **For Businesses**: Prioritize mobile-first strategies\n3. **For Policymakers**: Strengthen digital payment regulations\n\n### Conclusion\nMyanmar''s digital economy presents significant opportunities for stakeholders willing to navigate its unique challenges.\n\n---\n*ဒီလို Professional + Article style က data-driven, authoritative content အတွက် သင့်တော်ပါတယ်။*', 2),

('Casual', 'Blog Post', '✨', 'Friendly, relatable content that feels like chatting with a friend', 'သူငယ်ချင်းနဲ့ စကားပြောသလို ရင်းနှီးပြီး ချစ်စဖွယ် content', 'Personal blogs, lifestyle content, community building', 'ကိုယ်ရေးကိုယ်တာ blog များ၊ lifestyle content၊ community တည်ဆောက်ရေး', 'ဟေ့ ဒီနေ့ ကျွန်တော် ကော်ဖီဆိုင်မှာ...', E'# ✨ Casual + Blog Post Example\n\n## ခေါင်းစဉ်: "ဒီနေ့ ကော်ဖီဆိုင်မှာ သိလိုက်ရတဲ့ Life Lesson"\n\nဟေ့ မင်းတို့!\n\nဒီနေ့ ကျွန်တော် favorite ကော်ဖီဆိုင်လေးမှာ ထိုင်ရင်း... တစ်ခုခု သိလိုက်ရတယ်။\n\n### ဖြစ်သွားတာက ဒီလိုပါ\n\nကျွန်တော် laptop ဖွင့်ပြီး အလုပ်လုပ်နေတုန်း... ဘေးက စားပွဲမှာ uncle တစ်ယောက် ရောက်လာတယ်။\n\nသူက phone ကို ကိုင်ပြီး... **TikTok လုပ်နေတာ!** 😲\n\nAge: ခန့်မှန်းခြေ ၆၀ ကျော်။\nContent: ချက်ပြုတ်နည်း။\nFollowers: ၅သောင်းကျော်။\n\n### ကျွန်တော် သိလိုက်တာက...\n\n> "Too old" ဆိုတာ excuse ပဲ။ "Too busy" ဆိုတာလည်း excuse ပဲ။\n\nဒီ uncle က ကျွန်တော့်ထက် technology မသိဘူး။ ဒါပေမယ့် သူက **စခဲ့တယ်။ လုပ်ခဲ့တယ်။ အခု အောင်မြင်နေပြီ။**\n\n### So... မင်းကော?\n\nစချင်တာ ရှိရင်... ဒီနေ့ပဲ စလိုက်ပါ။ Perfect မဖြစ်လည်း ရပါတယ်။\n\nကျွန်တော်တို့ လမ်းမှာ တွေ့မယ်နော်! ☕\n\n---\n*ဒီလို Casual + Blog Post style က ရင်းနှီးပြီး relatable ဖြစ်စေပါတယ်။*', 3),

('Inspiring', 'Script', '🎬', 'Emotionally powerful video scripts that move audiences to action', 'စိတ်ခံစားမှုကို ထိထိမိမိ ဆွဲဆောင်နိုင်တဲ့ video script', 'YouTube videos, motivational content, brand storytelling', 'YouTube video များ၊ motivation content၊ brand story များ', '[V.O.] ဒီနေ့ကနေပဲ အရာအားလုံး ပြောင်းလဲသွားနိုင်တယ်...', E'# 🎬 Inspiring + Script Example\n\n## ခေါင်းစဉ်: "The Journey" - Motivational Video Script\n\n---\n\n**[FADE IN]**\n\n**[SCENE: Dark room, single spotlight on empty chair]**\n\n**V.O. (Voice Over):**\n> "လူတိုင်းမှာ story တစ်ခု ရှိတယ်..."\n\n**[MONTAGE: Various people facing struggles]**\n\n**V.O.:**\n> "ကျရှုံးခဲ့ဖူးတယ်။ လဲကျခဲ့ဖူးတယ်။ မျက်ရည်ကျခဲ့ဖူးတယ်။"\n\n**[BEAT - 2 seconds silence]**\n\n**[SCENE: Sun rising over mountains]**\n\n**V.O. (Intensity builds):**\n> "ဒါပေမယ့်... **ပြန်ထလာခဲ့တယ်။**"\n\n**[MONTAGE: Same people now succeeding]**\n\n**V.O.:**\n> "အောင်မြင်သူတွေက မကျရှုံးဖူးလို့ မဟုတ်ဘူး...\n> **ထပ်ထပ်ကြိုးစားလို့။**"\n\n**[SCENE: Close-up of determined eyes]**\n\n**V.O. (Climax):**\n> "မင်းရဲ့ story က ဘယ်လိုဖြစ်မလဲ?\n> **ဒီနေ့ကနေပဲ ရေးစလိုက်ပါ။**"\n\n**[LOGO REVEAL with tagline]**\n\n**SUPER:** "Your Story Starts Now."\n\n**[FADE OUT]**\n\n---\n*ဒီလို Inspiring + Script style က emotional impact ရှိပြီး action ယူစေပါတယ်။*', 4),

('Friendly', 'Tutorial', '📚', 'Step-by-step guides that make complex topics easy to understand', 'ရှုပ်ထွေးတဲ့ အကြောင်းအရာတွေကို လွယ်လွယ်ကူကူ နားလည်အောင် ရှင်းပြပေးတဲ့ guide', 'How-to guides, educational content, onboarding materials', 'How-to guide များ၊ သင်ကြားရေး content၊ onboarding material များ', 'အဆင့် ၁: ပထမဆုံး Canva ကို ဖွင့်လိုက်ပါ...', E'# 📚 Friendly + Tutorial Example\n\n## ခေါင်းစဉ်: "Canva နဲ့ ပထမဆုံး Social Media Post ဖန်တီးနည်း"\n\nဟိုင်း! ဒီနေ့ Canva သုံးပြီး လှပတဲ့ social media post တစ်ခု ဖန်တီးကြမယ်နော်! 🎨\n\n### 📋 လိုအပ်တာတွေ\n- Canva account (အခမဲ့)\n- Internet connection\n- ၁၀ မိနစ် အချိန်\n\n---\n\n### အဆင့် ၁: Canva ကို ဖွင့်ပါ\n\n1. [canva.com](https://canva.com) ကို သွားပါ\n2. **"Sign up"** ကို နှိပ်ပါ (Google နဲ့ဆို ပိုမြန်တယ်)\n3. Account ရပြီဆိုရင် Dashboard ကို ရောက်ပါပြီ! ✅\n\n### အဆင့် ၂: Template ရွေးပါ\n\n1. Search bar မှာ **"Instagram Post"** ရိုက်ပါ\n2. ကြိုက်တဲ့ template ကို နှိပ်ပါ\n3. **"Customize this template"** ကို နှိပ်ပါ\n\n> 💡 **Tip:** အခမဲ့ template တွေက "Free" badge ပါတယ်!\n\n### အဆင့် ၃: Edit လုပ်ပါ\n\n| လုပ်ချင်တာ | နှိပ်ရမှာ |\n|-----------|----------|\n| စာပြင်ချင်ရင် | စာပေါ် click |\n| ပုံပြင်ချင်ရင် | ပုံပေါ် click |\n| အသစ်ထည့်ချင်ရင် | ဘယ်ဘက် menu |\n\n### အဆင့် ၄: Download လုပ်ပါ\n\n1. ညာဘက်အပေါ် **"Share"** ကို နှိပ်ပါ\n2. **"Download"** ကို ရွေးပါ\n3. PNG format ရွေးပြီး download နှိပ်ပါ\n\n### 🎉 ပြီးပါပြီ!\n\nအခု မင်းရဲ့ ပထမဆုံး design ရပြီ! မခက်ဘူးနော်?\n\n---\n*ဒီလို Friendly + Tutorial style က step-by-step ရှင်းပြပြီး beginner-friendly ဖြစ်စေပါတယ်။*', 5),

('Formal', 'News', '📰', 'Objective, fact-based reporting with professional journalism standards', 'ကျွမ်းကျင်သော သတင်းစကားလုံးဖွဲ့စည်းမှုနှင့် အချက်အလက်အခြေခံ သတင်းရေးသားခြင်း', 'Press releases, company announcements, official communications', 'သတင်းထုတ်ပြန်ချက်များ၊ ကုမ္ပဏီကြေညာချက်များ၊ တရားဝင် ဆက်သွယ်ရေး', 'ယနေ့ ကုမ္ပဏီဘုတ်အဖွဲ့မှ CEO အသစ် ခန့်အပ်ကြောင်း...', E'# 📰 Formal + News Example\n\n## ခေါင်းစဉ်: "TechCorp Myanmar Appoints New Chief Executive Officer"\n\n**YANGON, Myanmar — December 18, 2024**\n\nTechCorp Myanmar Limited today announced the appointment of U Aung Kyaw as Chief Executive Officer, effective January 1, 2025.\n\n### Official Statement\n\nThe Board of Directors released the following statement:\n\n> "Following a comprehensive global search, we are pleased to announce U Aung Kyaw as our new CEO. His extensive experience in technology and proven leadership track record make him the ideal candidate to lead TechCorp Myanmar into its next phase of growth."\n\n### Executive Background\n\n**U Aung Kyaw** brings over 20 years of experience in the technology sector:\n\n- **Previous Role:** Chief Operating Officer, Digital Solutions Inc. (2019-2024)\n- **Education:** MBA, Stanford Graduate School of Business\n- **Notable Achievements:** Led digital transformation initiatives generating $50M in new revenue\n\n### Company Overview\n\nTechCorp Myanmar Limited is a leading technology solutions provider, serving over 500 enterprise clients across Southeast Asia.\n\n### Media Contact\n\n**Daw Su Su Hlaing**\nHead of Corporate Communications\nEmail: communications@techcorp.com.mm\nPhone: +95-1-234-5678\n\n---\n\n*This press release contains forward-looking statements. Actual results may differ materially from those projected.*\n\n---\n*ဒီလို Formal + News style က professional, objective reporting အတွက် သင့်တော်ပါတယ်။*', 6);