-- Add AI usage tracking columns to srt_translations
ALTER TABLE public.srt_translations 
ADD COLUMN IF NOT EXISTS ai_tokens_input INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ai_tokens_output INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ai_tokens_total INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ai_cost_estimate DECIMAL(10, 6) DEFAULT 0,
ADD COLUMN IF NOT EXISTS ai_model_used TEXT,
ADD COLUMN IF NOT EXISTS processing_time_ms INTEGER;

-- Add comments
COMMENT ON COLUMN public.srt_translations.ai_tokens_input IS 'Input tokens used for transcription and translation';
COMMENT ON COLUMN public.srt_translations.ai_tokens_output IS 'Output tokens generated by AI';
COMMENT ON COLUMN public.srt_translations.ai_tokens_total IS 'Total tokens used (input + output)';
COMMENT ON COLUMN public.srt_translations.ai_cost_estimate IS 'Estimated cost in USD based on model pricing';
COMMENT ON COLUMN public.srt_translations.ai_model_used IS 'AI model used for processing';
COMMENT ON COLUMN public.srt_translations.processing_time_ms IS 'Total processing time in milliseconds';

-- Create subtitle styles table
CREATE TABLE public.srt_subtitle_styles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  style_name TEXT NOT NULL DEFAULT 'Default',
  is_default BOOLEAN DEFAULT false,
  
  -- Font Settings
  font_family TEXT DEFAULT 'Arial',
  font_size INTEGER DEFAULT 24,
  font_weight TEXT DEFAULT 'normal',
  
  -- Color Settings
  text_color TEXT DEFAULT '#FFFFFF',
  background_color TEXT DEFAULT 'rgba(0,0,0,0.8)',
  outline_color TEXT DEFAULT '#000000',
  outline_width INTEGER DEFAULT 2,
  
  -- Position Settings
  position TEXT DEFAULT 'bottom',
  vertical_margin INTEGER DEFAULT 50,
  horizontal_padding INTEGER DEFAULT 16,
  
  -- Effects
  shadow_enabled BOOLEAN DEFAULT true,
  animation_type TEXT DEFAULT 'fade',
  
  -- Word Tracking (Karaoke-style)
  word_highlight_enabled BOOLEAN DEFAULT false,
  word_highlight_color TEXT DEFAULT '#FFD700',
  
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.srt_subtitle_styles ENABLE ROW LEVEL SECURITY;

-- RLS Policies for subtitle styles
CREATE POLICY "Users can view their own styles"
ON public.srt_subtitle_styles
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own styles"
ON public.srt_subtitle_styles
FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own styles"
ON public.srt_subtitle_styles
FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own styles"
ON public.srt_subtitle_styles
FOR DELETE
USING (auth.uid() = user_id);

-- Trigger for updated_at
CREATE TRIGGER update_srt_subtitle_styles_updated_at
BEFORE UPDATE ON public.srt_subtitle_styles
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();